bookr/bookr/urls.py
from django.contrib import admin
# from reviews.admin import admin_site
from django.urls import path, include
import reviews.views


urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('reviews.urls')), 
]

bookr/reviews/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    # Homepage
    # path('', views.index, name='index'),

    # Search Page
    # path('book-search', views.search, name='book-search')

    path('', views.welcome_view, name='welcome_view'),
    path('books/', views.book_list, name='book_list'),
    path('books/<int:details_id>', views.book_details, name='book_details')
]

bookr/reviews/models.py
from django.db import models
from django.contrib import auth

class Publisher(models.Model):
    """A company that publishes books"""
    name = models.CharField(max_length=50, help_text="The name of the Publisher.")
    website = models.URLField(help_text="The Publisher's website.")
    email = models.EmailField(help_text="The Publisher's email address.")
    def __str__(self):
        return self.name

class Book(models.Model):
    """A published book."""
    title = models.CharField(max_length=70, help_text="The title of the book.")
    publication_date = models.DateField(verbose_name="Date the book was published.")
    isbn = models.CharField(max_length=20, verbose_name="ISBN number of the book.")
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    contributors = models.ManyToManyField('Contributor', through="BookContributor")
    def __str__(self):
        # return "{} ({})".format(self.title, self.isbn)
        return f"{self.title} ({self.isbn})"

    def isbn13(self):
        return "{}-{}-{}-{}-{}".format(self.isbn[0:3], self.isbn[3:4], \
            self.isbn[4:6], self.isbn[6:12], self.isbn[12:13])
    

class Contributor(models.Model):
    """A contributor to a Book, e.g. author, editor, co-author."""
    first_names = models.CharField(max_length=50, help_text="The contributor's first name or names.")
    last_names = models.CharField(max_length=50, help_text="The contributor's last name or names.")
    email = models.EmailField(help_text="The contact email for the contributor.")

    def initialled_name(self):
        initials = ''.join([name[0] for name in self.first_names.split(' ')])
        return f"{initials}"

    def __str__(self):
        return self.last_names, self.initialled_name()
class BookContributor(models.Model):
    class ContributionRole(models.TextChoices):
        AUTHOR = "AUTHOR", "Author"
        CO_AUTHOR = "CO_AUTHOR", "Co-Author"
        EDITOR = "EDITOR", "Editor"

    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    contributor = models.ForeignKey(Contributor, on_delete=models.PROTECT)
    role = models.CharField(verbose_name="The role this contributor had in the book.", choices=ContributionRole.choices, max_length=20)

class Review(models.Model):
    content = models.TextField(help_text="The Review text.")
    rating = models.IntegerField(help_text="The rating the reviewer has given.")
    date_created = models.DateTimeField(auto_now_add=True, help_text="The date and time the review was created.")
    date_edited = models.DateTimeField(null=True, help_text="The date and time the review was last edited.")
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, help_text="The Book that this review is for.")

bookr/reviews/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, Review
from .utils import average_rating


def welcome_view(request):
    # message = f"<html><h1>Welcome to Bookr!</h1> <p>{Book.objects.count()} books and counting!</p></html>"
    return render(request, 'reviews/base.html')

def book_list(request):
    books = Book.objects.all()
    book_list = []
    for book in books:
        reviews = book.review_set.all()
        if reviews:
            book_rating = average_rating([review.rating for review in reviews])
            number_of_reviews = len(reviews)
        else:
            book_rating = None
            number_of_reviews = 0
        book_list.append({'book': book,\
                    'book_rating': book_rating,\
                    'number_of_reviews': number_of_reviews})
    context = {'book_list': book_list}
    return render(request, 'reviews/book_list.html', context)

def book_details(request, details_id):
    # details = Book.objects.get(id=details_id)
    details = get_object_or_404(Book, id=details_id)
    comments = details.review_set.order_by('date_created')
    reviews = details.review_set.all()
    if reviews:
        book_rating = average_rating([review.rating for review in reviews])
        context = {
            "details": details,
            "book_rating": book_rating,
            "comments": comments,
            "reviews": reviews
        }
    else:
        context = {
            "details": details,
            "book_rating": None,
            "comments": None, 
            "reviews": None
        }
    return render(request, 'reviews/book_details.html', context)

bookr/reviews/templates/book_details.html
{% extends 'base.html' %}

{% block content %}
<h3>Book Details</h3>
<ul class="list-group">
    
    <li class="list-group-item">
        <span class="text-info">Title: </span><span>{{ details }}</span><br>
        <span class="text-info">Publisher: </span><span>{{ details.publisher }}</span><br>
        <span class="text-info">Publication Date: </span><span>{{ details.publication_date }}</span><br>
        {% if not reviews %}
            <hr>
            <h3>Be the first one to write a review.</h3>
        {% else %}
        <span class="text-info">Overall Rating: </span><span class="badge badge-pill badge-primary">{{ book_rating }}</span><br>
    </li>
</ul>
<br>
<h3>Review Comments</h3>
<ul class="list-group">
    {% for comment in comments %}
    <li class="list-group-item ml-5">
        <span class="text-info">Review comment: </span><span>{{ comment.content }}</span><br>
        <span class="text-info">Created on: </span><span>{{ comment.date_created }}</span><br>
        <span class="text-info">Modified on: </span><span>{{ comment.date_edited }}</span><br>
        <span class="text-info">Rating: </span><span class="badge badge-pill badge-secondary">{{ comment.rating }}</span><br>
        <span class="text-info">Creator: </span><span>{{ comment.creator }}</span><br>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock content %}

bookr/reviews/templates/book_list.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-group">
    {% for book in book_list %}
    <li class="list-group-item">
        <span class="text-info">Title: </span><span>{{ book.book.title }}</span><br>
        <span class="text-info">Publisher: </span><span>{{ book.book.publisher }}</span><br>
        <span class="text-info">Publication Date: </span><span>{{ book.book.publication_date }}</span><br>
        <span class="text-info">Rating: </span><span class="badge badge-pill badge-primary">{{ book.book_rating }}</span><br>
        <span class="text-info">Number of reviews: </span><span >{{ book.number_of_reviews }}</span><br>
        {% if book.book_rating is null %}
        <span class="text-secondary"> Provide a rating and write the first review for this book.</span><br>
        {% endif %}
        <a href="/books/{{ book.book.id }}"><button type="button" class="btn btn-sm btn-primary">Reviews</button></a>
    </li>
    <br>
    {% endfor %}
</ul>
{% endblock content %}

bookr/reviews/templates/reviews/base.html
{% extends 'base.html' %}
{% load static %}

{% block brand %}

<img src="{% static 'reviews/logo.png' %}">

{% endblock brand %}

bookr/reviews/templates/reviews/book_details.html
{% extends 'reviews/base.html' %}
{% load static %}

{% block content %}
<h3>Book Details</h3>
<ul class="list-group">
    
    <li class="list-group-item">
        <span class="text-info">Title: </span><span>{{ details }}</span><br>
        <span class="text-info">Publisher: </span><span>{{ details.publisher }}</span><br>
        <span class="text-info">Publication Date: </span><span>{{ details.publication_date }}</span><br>
        {% if not reviews %}
            <hr>
            <h3>Be the first one to write a review.</h3>
        {% else %}
        <span class="text-info">Overall Rating: </span><span class="badge badge-pill badge-primary">{{ book_rating }}</span><br>
    </li>
</ul>
<br>
<h3>Review Comments</h3>
<ul class="list-group">
    {% for comment in comments %}
    <li class="list-group-item ml-5">
        <span class="text-info">Review comment: </span><span>{{ comment.content }}</span><br>
        <span class="text-info">Created on: </span><span>{{ comment.date_created }}</span><br>
        <span class="text-info">Modified on: </span><span>{{ comment.date_edited }}</span><br>
        <span class="text-info">Rating: </span><span class="badge badge-pill badge-secondary">{{ comment.rating }}</span><br>
        <span class="text-info">Creator: </span><span>{{ comment.creator }}</span><br>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock content %}

bookr/reviews/templates/reviews/book_list.html
{% extends 'reviews/base.html' %}
{% load static %}

{% block content %}
<ul class="list-group">
    {% for book in book_list %}
    <li class="list-group-item">
        <span class="text-info">Title: </span><span>{{ book.book.title }}</span><br>
        <span class="text-info">Publisher: </span><span>{{ book.book.publisher }}</span><br>
        <span class="text-info">Publication Date: </span><span>{{ book.book.publication_date }}</span><br>
        <span class="text-info">Rating: </span><span class="badge badge-pill badge-primary">{{ book.book_rating }}</span><br>
        <span class="text-info">Number of reviews: </span><span >{{ book.number_of_reviews }}</span><br>
        {% if book.book_rating is null %}
        <span class="text-secondary"> Provide a rating and write the first review for this book.</span><br>
        {% endif %}
        <a href="/books/{{ book.book.id }}"><button type="button" class="btn btn-sm btn-primary">Reviews</button></a>
    </li>
    <br>
    {% endfor %}
</ul>
{% endblock content %}

bookr/reviews/templates/reviews/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results for {{ results }}</title>
</head>
<body>
    <h1>Search Results for <em>{{ results }}</em></h1>
</body>
</html>

bookr/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Book Review</title>

    <style>
      .navbar-brand > img {
        height: 60px;
      }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
       <a class="navbar-brand" href="{% url 'reviews:welcome_view' %}">{% block brand %} {% endblock brand %}</a>
     
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Logout</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      {% block content %}
      <main role="main" class="container">
        <div class="pb-2 mb-2 mt-2 border-bottom">
          <h1>Welcome to Bookr</h1>
          <a href="{% url 'reviews:book_list' %}"><button class="btn btn-success my-2 my-sm-0" type="submit">Go To Book List</button></a>
       </div>
      </main>
      {% endblock content %}

</body>
</html>